### PR TITLE
fix security author authenticity

### PR DESCRIPTION
**Pull request by fabiooshiro**
#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [x] api
- [ ] frontend
- [ ] lib

### CODE REVIEW

**Comment by DimiMikadze** [comment]
Hi @fabiooshiro, thanks for the PR, but I don't understand how these changes will prevent a hacker from posting a comment with the different user names?

To prevent it, I think will need to check if `author` and `authUser.id` are the same, and create a comment only if they are.

**Comment by fabiooshiro** [comment]
Just getting the id from the JWT is enough...

Em sáb, 5 de set de 2020 05:56, Dimi Mikadze <notifications@github.com>
escreveu:

**Comment by DimiMikadze** [comment]
Hi @fabiooshiro, in the [issue](https://github.com/DimiMikadze/create-social-network/issues/65) you have explained that `post` creation contains a bug, but this PR contains the changes for `comments`. 

As explained in [CONTRIBUTING.md](https://github.com/DimiMikadze/create-social-network/issues/65) let's first discover what's causing the issue, and describe it by respecting the issue template.

Then agree on how we are going to approach it, and finally create a PR.

**Comment by fabiooshiro** [comment]
All the system has the same problem...

**Pull request closed without merging**
