### PR TITLE
Message ui enhancements

### PR DESCRIPTION
**Pull request by leventdeniz**
#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] api
- [x] frontend
- [ ] lib

### CODE REVIEW

**Comment by DimiMikadze** [comment]
@leventdeniz I'm closing this right now in favor to: https://github.com/udilia/create-social-network/issues/21#issuecomment-546992650 I'll make sure to create clear sub tasks, which you can assign on yourself and start working on them 👍Thank You!

**Comment by leventdeniz** [comment]
@DimiMikadze So you'll create a task for this, I'll assign myself and push these exact changes again or how are we going to proceed?

**Comment by DimiMikadze** [comment]
@leventdeniz Yes I'll create tasks and you'll choose whichever you want and push the changes of it, not this exact changes, the ones that task will require.

**Comment by leventdeniz** [comment]
Ok, I'll see if there is anything that I'd like to work on

**Pull request closed without merging**
